---
version: '2.2'
services:
  local-azure:
    image: mcr.microsoft.com/azure-storage/azurite
  azcli:
    image: mcr.microsoft.com/azure-cli
    entrypoint: az
    environment:
      - AZURE_CORE_OUTPUT=json
  python:
    build:
      context: .
  blobstore:
    extends: local-azure
    entrypoint: azurite-blob
    ports:
      - 10000:10000
    command:
      - -d
      - debug.log
      - --blobHost
      - 0.0.0.0
      - --blobPort
      - "10000"
  hello-azure:
    extends: python
    environment:
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=5000
    ports:
      - 80:5000
    entrypoint: python
    command: hello_azure.py
