---
version: '2.2'
services:
  local-azure:
    image: mcr.microsoft.com/azure-storage/azurite
  azcli:
    image: mcr.microsoft.com/azure-cli
    entrypoint: az
    environment:
      - AZURE_CORE_OUTPUT=json
  python:
    build:
      context: .
  database:
    image: postgres:alpine
    volumes:
      - $PWD/scripts/db_init:/docker-entrypoint-initdb.d
    ports:
      - 5432
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: sessions
  blobstore:
    extends: local-azure
    entrypoint: azurite-blob
    ports:
      - 10000:10000
    command:
      - -d
      - debug.log
      - --blobHost
      - 0.0.0.0
      - --blobPort
      - "10000"
  hello-azure:
    depends_on:
      - database
    extends: python
    environment:
      FLASK_HOST: "0.0.0.0"
      FLASK_PORT: "5000"
      SESSION_DB_USER: dbuser
      SESSION_DB_PASSWORD: supersecret # don't do it like this in prod!
      SESSION_DB_HOST: database
      SESSION_DB_PORT: "5432"
    ports:
      - 80:5000
    entrypoint: python
    command: hello_azure.py
