---
version: '2.2'
services:
  local-azure:
    image: mcr.microsoft.com/azure-storage/azurite
  azcli:
    image: mcr.microsoft.com/azure-cli
    entrypoint: az
    environment:
      - AZURE_CORE_OUTPUT=json
    volumes:
      - $HOME/.azure:/root/.azure
  gpg-infra:
    image: vladgh/gpg
    volumes:
      - $PWD/infra:/app
    working_dir: /app
  python:
    build:
      context: .
  database:
    image: postgres:alpine
    volumes:
      - $PWD/scripts/db_init:/docker-entrypoint-initdb.d
    ports:
      - 5432
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: sessions
  terraform:
    image: hashicorp/terraform
    volumes:
      - $PWD/infra:/infra:cached
      - $PWD/scripts:/scripts:ro,cached
    working_dir: /infra
    env_file: infra/.env
    entrypoint:
      - sh
      - /scripts/execute_terraform.sh
  blobstore:
    extends: local-azure
    entrypoint: azurite-blob
    ports:
      - 10000:10000
    command:
      - azurite-blob
      - -d
      - debug.log
      - --blobHost
      - 0.0.0.0
      - --blobPort
      - "10000"
  hello-azure:
    depends_on:
      - database
      - blobstore
    extends: python
    environment:
      FLASK_HOST: "0.0.0.0"
      FLASK_PORT: "5000"
      SESSION_DB_USER: dbuser
      SESSION_DB_PASSWORD: supersecret # don't do it like this in prod!
      SESSION_DB_HOST: database
      SESSION_DB_PORT: "5432"
      AZURE_STORAGE_ACCOUNT_NAME: devstoreaccount1
      AZURE_STORAGE_ACCOUNT_KEY: Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==
      AZURE_STORAGE_ENDPOINT: http://blobstore:10000
    ports:
      - 80:5000
    entrypoint: python
    command: hello_azure.py
  hello-azure-debug:
    depends_on:
      - database
      - blobstore
    extends: python
    environment:
      LOG_LEVEL: DEBUG
      FLASK_HOST: "0.0.0.0"
      FLASK_PORT: "5000"
      SESSION_DB_USER: dbuser
      SESSION_DB_PASSWORD: supersecret # don't do it like this in prod!
      SESSION_DB_HOST: database
      SESSION_DB_PORT: "5432"
      AZURE_STORAGE_ACCOUNT_NAME: devstoreaccount1
      AZURE_STORAGE_ACCOUNT_KEY: Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==
      AZURE_STORAGE_ENDPOINT: http://blobstore:10000
    ports:
      - 80:5000
    entrypoint: python
    command: hello_azure.py
  init-database:
    depends_on:
      - database
    extends: database
    entrypoint: sh
    environment:
      SESSION_DB_USER: dbuser
      SESSION_DB_PASSWORD: supersecret # don't do it like this in prod!
      SESSION_DB_HOST: database
      SESSION_DB_PORT: "5432"
    volumes:
      - $PWD:/app:ro,cached
    working_dir: /app
    command:
      - -c
      - scripts/load_database.sh
  init-blobstore:
    depends_on:
      - blobstore
    extends: azcli
    entrypoint: sh
    environment:
      AZURE_STORAGE_ACCOUNT_NAME: devstoreaccount1
      AZURE_STORAGE_ACCOUNT_KEY: Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==
      AZURE_STORAGE_ENDPOINT: http://blobstore:10000
    volumes:
      - $PWD:/app:ro,cached
    working_dir: /app
    command:
      - -c
      - scripts/load_blobstore.sh
  encrypt-env:
    extends: gpg-infra
    command:
      - --batch
      - --yes
      - --passphrase=$ENV_PASSWORD
      - --output=env.gpg
      - --symmetric
      - .env
  decrypt-env:
    extends: gpg-infra
    command:
      - '--decrypt'
      - '--batch'
      - "--passphrase=$ENV_PASSWORD"
      - '--output=.env'
      - env.gpg
