---
- hosts: localhost
  gather_facts: no
  connection: local
  tasks:
    - name: Install Postgres
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - postgresql
        - postgresql-contrib

    - name: Install psycopg2
      package:
        name: python-psycopg2
        state: present

    - name: Start Postgres
      service:
        name: postgresql
        state: started

    - name: Allow Postgres to listen to external connection requests
      become: true
      become_method: su
      become_user: postgres
      postgresql_set:
        name: listen_addresses
        value: "*"

    - name: Restart postgres
      service:
        name: postgresql
        state: restarted
